const test = require('node:test');
const assert = require('node:assert/strict');
const Client = require('../src/models/Client');
const Request = require('../src/models/ClientDeactivation');
const Lead = require('../src/models/Lead');
const service = require('../src/services/clientDeactivation');
const userId = '64b000000000000000000001';
const clientId = '64b000000000000000000002';
const managerId = '64b000000000000000000003';
const adminId = '64b000000000000000000004';
const query = (row) => ({ populate() { return this; }, select() { return this; }, lean: async () => row });
const response = () => ({ code: 200, body: null, status(code) { this.code = code; return this; }, json(body) { this.body = body; return this; } });

test('request requires a reason and manager; locks every company service record', async (t) => {
  const client = { _id: clientId, companyIdentity: 'ccl', data: { basic: { clientLegalName: 'CCL' } } };
  t.mock.method(Client, 'findOne', () => query(client));
  t.mock.method(Lead, 'find', () => query([]));
  t.mock.method(Client, 'find', () => query([client, { ...client, _id: adminId }]));
  t.mock.method(Request, 'findOne', () => query(null));
  t.mock.method(Request, 'create', async (data) => data);
  let res = response();
  await service.request({ params: { id: clientId }, user: { _id: userId, role: 'operation', managerId }, body: { reason: 'Contract ended' } }, res);
  assert.equal(res.body.request.status, 'MANAGER_PENDING');
  assert.equal(res.body.request.clientIds.length, 2);
  assert.equal(res.body.request.history[0].reason, 'Contract ended');
  res = response();
  await service.request({ params: { id: clientId }, user: { _id: userId, role: 'operation' }, body: { reason: 'End' } }, res);
  assert.equal(res.code, 400);
  res = response();
  await service.request({ params: { id: clientId }, user: { _id: userId }, body: { reason: ' ' } }, res);
  assert.equal(res.code, 400);
});
test('manager must approve before admin; rejection restores active access; reasons are recorded', async (t) => {
  let stored = { _id: clientId, requestedBy: userId, managerId, status: 'MANAGER_PENDING' };
  t.mock.method(Request, 'findById', () => query(stored));
  t.mock.method(Request, 'findOneAndUpdate', async (filter, update) => { assert.equal(filter.status, stored.status); stored = { ...stored, ...update.$set }; return { ...stored, event: update.$push.history }; });
  const run = async (user, decision, reason = 'Reviewed') => { const res = response(); await service.decide({ params: { requestId: clientId }, user, body: { decision, reason } }, res); return res; };
  assert.equal((await run({ _id: adminId, role: 'admin' }, 'APPROVE')).code, 403);
  assert.equal((await run({ _id: adminId, role: 'manager' }, 'APPROVE')).code, 403);
  const manager = await run({ _id: managerId, role: 'manager' }, 'APPROVE');
  assert.equal(manager.body.request.status, 'ADMIN_PENDING');
  assert.equal(manager.body.request.event.reason, 'Reviewed');
  assert.equal((await run({ _id: adminId, role: 'superadmin' }, 'APPROVE')).body.request.status, 'INACTIVE');
  assert.equal((await run({ _id: adminId, role: 'admin' }, 'REJECT')).code, 403);
  stored.status = 'ADMIN_PENDING';
  assert.equal((await run({ _id: adminId, role: 'admin' }, 'REJECT')).body.request.status, 'REJECTED');
  assert.equal(service.locked(stored.status), false);
  stored.status = 'MANAGER_PENDING';
  assert.equal((await run({ _id: managerId, role: 'manager' }, 'REJECT')).body.request.status, 'REJECTED');
  assert.equal((await run({ _id: managerId, role: 'manager' }, 'APPROVE', '')).code, 400);
});
test('API blocks edits for pending and inactive records including administrator writes', async (t) => {
  t.mock.method(Client, 'findById', () => query({ _id: clientId, companyIdentity: 'ccl' }));
  t.mock.method(Request, 'findOne', () => query({ status: 'INACTIVE' }));
  const res = response();
  let advanced = false;
  await service.guard({ method: 'PUT', path: '/', params: { id: clientId }, body: {}, user: { role: 'admin' } }, res, () => { advanced = true; });
  assert.equal(res.code, 423);
  assert.equal(advanced, false);
});
