const mongoose = require('mongoose');

const LeadSchema = new mongoose.Schema({
  leadCode: { type: String, trim: true, unique: true, sparse: true },
  sourceLeadId: { type: String, trim: true },
  ccpLeadId: { type: String, trim: true, index: true },
  externalLeadId: { type: String, trim: true, index: true },
  communicationMode: { type: String, trim: true },
  status: { type: String, trim: true },
  company: { type: String, trim: true },
  industryType: { type: String, trim: true },
  eprCategory: { type: String, trim: true },
  piboParent: { type: String, enum: ['PIBO', 'SIMP', 'PWP'], trim: true },
  piboCategoryParent: { type: String, enum: ['PIBO', 'SIMP', 'PWP'], trim: true },
  piboCategory: { type: String, trim: true },
  servicesOffered: { type: String, trim: true },
  addressLine1: { type: String, trim: true },
  addressLine2: { type: String, trim: true },
  addressLine3: { type: String, trim: true },
  landmark: { type: String, trim: true },
  state: { type: String, trim: true },
  city: { type: String, trim: true },
  pinCode: { type: String, trim: true },
  existingClient: { type: String, enum: ['Yes', 'No'], default: 'No' },
  website: { type: String, trim: true },
  salutation: { type: String, trim: true },
  contactPerson: { type: String, trim: true },
  designation: { type: String, trim: true },
  emails: { type: String, trim: true },
  emailsSentCount: { type: Number, default: 0 },
  lastEmailSent: { type: String, trim: true },
  mobileNo1: { type: String, trim: true },
  mobileNo2: { type: String, trim: true },
  businessCardUrl: { type: String },
  referredBy: { type: String, trim: true },
  source: { type: String, trim: true },
  notes: { type: String, trim: true },
  assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  assignedToText: { type: String, trim: true },
  assignedBy: { type: String, trim: true },
  importedCreatedBy: { type: String, trim: true },
  updatedBy: { type: String, trim: true },
  closedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  closedByText: { type: String, trim: true },
  closedByEmail: { type: String, trim: true, lowercase: true },
  closedAt: { type: Date },
  leadDate: { type: String, trim: true },
  nextFollowUpDate: { type: String, trim: true },
  nextFollowUpTime: { type: String, trim: true },
  followUpRemarks: { type: String, trim: true },
  followUpHistory: { type: Array, default: [] },
  importedCreatedAt: { type: String, trim: true },
  importedUpdatedAt: { type: String, trim: true },
  workflowStatus: { type: String, enum: ['draft', 'submitted'], default: 'draft' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

module.exports = mongoose.model('Lead', LeadSchema);
