import React, { useEffect, useState } from 'react'
import { AlertTriangle, ArrowLeft, Building2, CalendarClock, Download, Flag, Loader2, Search, X } from 'lucide-react'
import api from '../../services/api'
import { API_ENDPOINTS } from '../../services/apiEndpoints'
import { formatDateTime } from '../../utils/productivityReportExports'

function downloadReport(report) { const lines = [['User', report.user?.name], ['Email', report.user?.email], ['Period', `${report.period?.from} to ${report.period?.to}`], [], ['Company', 'Lead Code', 'Status', 'Services', 'Follow-ups', 'Missed', 'Red Flags'], ...(report.leads || []).map((row) => [row.company, row.leadCode, row.status, row.services.map((item) => item.name).join('; '), row.followUps.length, row.missedFollowUps.length, row.redFlags.join('; ')])]; const csv = lines.map((row) => row.map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = `${report.user?.name || 'sales-user'}-sales-report.csv`; link.click(); URL.revokeObjectURL(link.href) }
function Stat({ label, value, note }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><small className="font-black uppercase tracking-wider text-slate-400">{label}</small><strong className="mt-2 block text-3xl text-slate-950">{value}</strong><p className="mt-1 text-xs font-semibold text-slate-500">{note}</p></article> }
function Status({ value }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${value === 'Closed' ? 'bg-emerald-100 text-emerald-700' : 'bg-sky-100 text-sky-700'}`}>{value}</span> }
function Empty({ text }) { return <p className="rounded-xl border border-dashed p-5 text-center text-sm font-bold text-slate-400">{text}</p> }

export default function UserWorkDrilldown({ user, from, to, onClose }) {
  const [report, setReport] = useState(null); const [company, setCompany] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { setLoading(true); api.get(API_ENDPOINTS.auth.userWorkReport(user.id), { params: { from, to } }).then(({ data }) => setReport(data)).catch((requestError) => setError(requestError?.response?.data?.error || 'Unable to load user work report.')).finally(() => setLoading(false)) }, [user.id, from, to])
  return <div className="fixed inset-0 z-[130] bg-slate-950/55 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="ml-auto flex h-full w-full max-w-7xl flex-col bg-[#f3f8f6] shadow-2xl">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 bg-white p-5"><div className="flex items-start gap-3">{company && <button type="button" onClick={() => setCompany(null)} className="grid h-10 w-10 place-items-center rounded-xl border"><ArrowLeft className="h-5 w-5"/></button>}<div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-700">{company ? 'Sales company analysis' : 'Sales user performance'}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{company?.company || user.name}</h2><p className="text-sm font-semibold text-slate-500">{company ? `${company.leadCode || 'Lead'} · Last activity ${formatDateTime(company.lastActivityAt)}` : `${user.email} · ${from} to ${to}`}</p></div></div><div className="flex gap-2">{report && !company && <button type="button" onClick={() => downloadReport(report)} className="flex h-10 items-center gap-2 rounded-xl bg-[#075848] px-4 text-sm font-black text-white"><Download className="h-4 w-4"/>Download Report</button>}<button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border bg-white"><X className="h-5 w-5"/></button></div></header>
    <div className="flex-1 overflow-y-auto p-5">{loading ? <div className="grid h-full place-items-center"><Loader2 className="h-9 w-9 animate-spin text-emerald-700"/></div> : error ? <div className="rounded-xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div> : company ? <SalesCompanyAnalysis company={company}/> : report && <UserAnalysis report={report} onCompany={setCompany}/>}</div>
  </section></div>
}

function UserAnalysis({ report, onCompany }) { const [status,setStatus]=useState('Open'); const [search,setSearch]=useState(''); const leads=report.leads.filter((lead)=>lead.status===status && lead.company.toLowerCase().includes(search.toLowerCase())); return <><section className="grid gap-3 sm:grid-cols-3"><Stat label="Total Leads" value={report.summary.leads} note="Created in selected period"/><Stat label="Lead Open" value={report.summary.openLeads} note="Work still in progress"/><Stat label="Lead Close" value={report.summary.closedLeads} note="Successfully closed leads"/></section><section className="mt-4 overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h3 className="flex items-center gap-2 font-black"><Building2 className="h-5 w-5 text-emerald-700"/>Sales Company Portfolio</h3><p className="text-xs font-semibold text-slate-500">Click a company to view services, follow-ups and risks.</p></div><div className="flex flex-wrap gap-2"><div className="flex rounded-xl bg-slate-100 p-1">{['Open','Closed'].map((value)=><button type="button" key={value} onClick={()=>setStatus(value)} className={`rounded-lg px-4 py-2 text-xs font-black ${status===value?'bg-emerald-700 text-white shadow':'text-slate-600'}`}>{value}</button>)}</div><label className="flex h-10 min-w-56 items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search company..." className="w-full bg-transparent text-sm font-semibold outline-none"/></label></div></div><div className="max-h-[55vh] overflow-auto"><table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-slate-50 text-left text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="p-3">Company</th><th>Services</th><th>Follow-ups</th><th>Missed</th><th>Red Flags</th><th>Last Activity</th><th>Status</th></tr></thead><tbody>{leads.map((lead)=><tr key={lead.id} className="border-t hover:bg-emerald-50/60"><td className="p-3"><button type="button" onClick={()=>onCompany(lead)} className="text-left font-black text-emerald-800 hover:underline">{lead.company}<small className="block font-semibold text-slate-400">{lead.leadCode || '-'}</small></button></td><td className="max-w-xs text-xs font-semibold">{lead.services.map((service)=>service.name).join(', ') || '-'}</td><td className="font-black">{lead.followUps.length}</td><td className={lead.missedFollowUps.length?'font-black text-orange-600':''}>{lead.missedFollowUps.length}</td><td className={lead.redFlags.length?'font-black text-rose-600':''}>{lead.redFlags.length}</td><td className="text-xs">{formatDateTime(lead.lastActivityAt)}</td><td><Status value={lead.status}/></td></tr>)}{!leads.length&&<tr><td colSpan="7" className="p-4"><Empty text={`No ${status.toLowerCase()} leads found.`}/></td></tr>}</tbody></table></div></section></> }

function SalesCompanyAnalysis({ company }) { return <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Services Added" value={company.services.length} note="Services added by this sales user"/><Stat label="Follow-ups" value={company.followUps.length} note="Complete follow-up record"/><Stat label="Missed Follow-ups" value={company.missedFollowUps.length} note="Overdue and still open"/><Stat label="Red Flags" value={company.redFlags.length} note={company.redFlags.length ? 'Needs immediate attention' : 'No active risk'}/></section><section className="mt-4 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><Panel title="Services Added" icon={Building2}>{company.services.map((service)=><div key={service.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><strong>{service.name}</strong><Status value={service.status}/></div><p className="mt-1 text-xs font-semibold text-slate-500">{[service.category, service.applicantType].filter(Boolean).join(' · ') || 'General service'}</p></div>)}</Panel><Panel title="Missed Follow-ups" icon={AlertTriangle} tone="rose">{company.missedFollowUps.length ? company.missedFollowUps.map((item,index)=><FollowUp key={`missed-${index}`} item={item} missed/>) : <Empty text="No missed follow-ups."/>}</Panel><Panel title="Red Flags" icon={Flag} tone="rose">{company.redFlags.length ? company.redFlags.map((flag)=><div key={flag} className="rounded-xl bg-rose-50 px-3 py-2 text-sm font-bold text-rose-700">{flag}</div>) : <Empty text="No red flags for this company."/>}</Panel></div><Panel title="Complete Follow-up Timeline" icon={CalendarClock}>{company.followUps.length ? company.followUps.map((item,index)=><FollowUp key={`${item.scheduledDate}-${index}`} item={item}/>) : <Empty text="No follow-up record available."/>}</Panel></section></> }
function Panel({ title, icon: Icon, tone, children }) { return <article className={`rounded-2xl border bg-white p-5 ${tone === 'rose' ? 'border-rose-200' : 'border-slate-200'}`}><h3 className="mb-4 flex items-center gap-2 font-black"><Icon className={`h-5 w-5 ${tone === 'rose' ? 'text-rose-600' : 'text-emerald-700'}`}/>{title}</h3><div className="space-y-3">{children}</div></article> }
function FollowUp({ item, missed }) { return <div className={`rounded-xl border p-3 ${missed ? 'border-rose-200 bg-rose-50' : 'border-slate-200 bg-slate-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{item.scheduledDate || 'Date not set'} {item.scheduledTime || ''}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-black ${item.closed ? 'bg-emerald-100 text-emerald-700' : missed ? 'bg-rose-100 text-rose-700' : 'bg-orange-100 text-orange-700'}`}>{item.closed ? 'Closed' : missed ? 'Missed' : 'Open'}</span></div><p className="mt-2 text-sm font-semibold text-slate-700">{item.remarks}</p><p className="mt-1 text-xs text-slate-500">{item.service} · {item.owner}</p>{item.reason && <p className="mt-1 text-xs font-semibold text-slate-600">Reason: {item.reason}</p>}</div> }
