import React, { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BarChart3, Building2, CheckCircle2, Download, FileText, Loader2, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import api from '../../services/api'
import { API_ENDPOINTS } from '../../services/apiEndpoints'
import { formatDateTime } from '../../utils/productivityReportExports'

const COLORS = ['#059669', '#f97316']
function downloadReport(report) { const lines = [['User', report.user?.name], ['Email', report.user?.email], ['Period', `${report.period?.from} to ${report.period?.to}`], [], ['Company', 'Lead Code', 'Status', 'Completion %', 'Filled Fields', 'Missing Fields'], ...(report.clients || []).map((row) => [row.company, row.leadCode, row.status, row.analysis.percentage, row.analysis.filledFields.join('; '), row.analysis.missingFields.join('; ')])]; const csv = lines.map((row) => row.map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = `${report.user?.name || 'user'}-work-report.csv`; link.click(); URL.revokeObjectURL(link.href) }
function Stat({ label, value, note }) { return <article className="rounded-2xl border border-slate-200 bg-white p-4"><small className="font-black uppercase tracking-wider text-slate-400">{label}</small><strong className="mt-2 block text-2xl text-slate-950">{value}</strong><p className="mt-1 text-xs font-semibold text-slate-500">{note}</p></article> }

export default function UserWorkDrilldown({ user, from, to, onClose }) {
  const [report, setReport] = useState(null); const [company, setCompany] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { setLoading(true); api.get(API_ENDPOINTS.auth.userWorkReport(user.id), { params: { from, to } }).then(({ data }) => setReport(data)).catch((requestError) => setError(requestError?.response?.data?.error || 'Unable to load user work report.')).finally(() => setLoading(false)) }, [user.id, from, to])
  const chart = useMemo(() => report ? [{ name: 'Leads', Total: report.summary.leads, Submitted: report.summary.submittedLeads }, { name: 'Client Masters', Total: report.summary.clientMasters, Submitted: report.summary.submittedClients }] : [], [report])
  const selectedPie = company ? [{ name: 'Filled', value: company.analysis.filled }, { name: 'Missing', value: company.analysis.missing }] : []
  return <div className="fixed inset-0 z-[130] bg-slate-950/55 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="ml-auto flex h-full w-full max-w-6xl flex-col bg-[#f3f8f6] shadow-2xl">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 bg-white p-5"><div className="flex items-start gap-3">{company && <button onClick={() => setCompany(null)} className="grid h-10 w-10 place-items-center rounded-xl border"><ArrowLeft className="h-5 w-5"/></button>}<div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-700">{company ? 'Company data analysis' : 'User work drill-down'}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{company?.company || user.name}</h2><p className="text-sm font-semibold text-slate-500">{company ? `${company.leadCode || 'Client Master'} · Last updated ${formatDateTime(company.updatedAt)}` : `${user.email} · ${from} to ${to}`}</p></div></div><div className="flex gap-2">{report && !company && <button onClick={() => downloadReport(report)} className="flex h-10 items-center gap-2 rounded-xl bg-[#075848] px-4 text-sm font-black text-white"><Download className="h-4 w-4"/>Download Report</button>}<button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border bg-white"><X className="h-5 w-5"/></button></div></header>
    <div className="flex-1 overflow-y-auto p-5">{loading ? <div className="grid h-full place-items-center"><Loader2 className="h-9 w-9 animate-spin text-emerald-700"/></div> : error ? <div className="rounded-xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div> : company ? <CompanyAnalysis company={company} pie={selectedPie}/> : report && <UserAnalysis report={report} chart={chart} onCompany={setCompany}/>}</div>
  </section></div>
}

function CompanyAnalysis({ company, pie }) { return <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Overall Completion" value={`${company.analysis.percentage}%`} note="Required Client Master fields"/><Stat label="Data Filled" value={company.analysis.filled} note={`of ${company.analysis.total} required fields`}/><Stat label="Data Missing" value={company.analysis.missing} note="Needs user attention"/><Stat label="Workflow Status" value={company.status || 'Draft'} note={`Approval: ${company.approvalStatus || '-'}`}/></section><section className="mt-4 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5"><h3 className="font-black">Filled vs Missing Data</h3><div className="h-64"><ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} label>{pie.map((entry, index) => <Cell key={entry.name} fill={COLORS[index]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></article><article className="rounded-2xl border bg-white p-5"><h3 className="font-black">Section-wise Completion</h3><div className="h-64"><ResponsiveContainer><BarChart data={company.analysis.sections} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" domain={[0,100]}/><YAxis dataKey="name" type="category" width={110} fontSize={10}/><Tooltip/><Bar dataKey="percentage" fill="#059669" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></article></section><section className="mt-4 grid gap-4 lg:grid-cols-2"><FieldList title="Filled Information" fields={company.analysis.filledFields} good/><FieldList title="Missing / Required Information" fields={company.analysis.missingFields}/></section></> }
function FieldList({ title, fields, good }) { return <article className={`rounded-2xl border bg-white p-5 ${good ? 'border-emerald-200' : 'border-orange-200'}`}><h3 className={`flex items-center gap-2 font-black ${good ? 'text-emerald-800' : 'text-orange-800'}`}>{good && <CheckCircle2 className="h-5 w-5"/>}{title}</h3><div className="mt-3 flex flex-wrap gap-2">{fields.map((field)=><span key={field} className={`rounded-full px-3 py-1.5 text-xs font-bold ${good ? 'bg-emerald-50 text-emerald-800' : 'bg-orange-50 text-orange-800'}`}>{field}</span>)}</div></article> }
function UserAnalysis({ report, chart, onCompany }) { return <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><Stat label="Total Leads" value={report.summary.leads} note="Created in report period"/><Stat label="Submitted Leads" value={report.summary.submittedLeads} note="Completed lead forms"/><Stat label="Client Masters" value={report.summary.clientMasters} note="Created by this user"/><Stat label="Submitted Clients" value={report.summary.submittedClients} note="Submitted records"/><Stat label="Avg. Completion" value={`${report.summary.averageCompletion}%`} note="Required data coverage"/><Stat label="Complete Clients" value={report.summary.completeClients} note="100% required fields"/><Stat label="Incomplete Clients" value={report.summary.incompleteClients} note="Need attention"/></section><section className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.5fr]"><article className="rounded-2xl border bg-white p-5"><h3 className="flex items-center gap-2 font-black"><BarChart3 className="h-5 w-5 text-emerald-600"/>Work Output</h3><div className="h-64"><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="Total" fill="#0f766e" radius={[6,6,0,0]}/><Bar dataKey="Submitted" fill="#f97316" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></article><CompanyList clients={report.clients} onCompany={onCompany}/></section><LeadList leads={report.leads}/></> }
function CompanyList({ clients, onCompany }) { return <article className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h3 className="flex items-center gap-2 font-black"><Building2 className="h-5 w-5 text-violet-600"/>Client Master Companies</h3><p className="text-xs font-semibold text-slate-500">Click company name for full completion analysis.</p></div><div className="max-h-72 overflow-auto">{clients.length ? clients.map((row)=><button key={row.id} onClick={() => onCompany(row)} className="flex w-full items-center justify-between gap-3 border-b px-4 py-3 text-left hover:bg-emerald-50"><span><strong className="block text-slate-950">{row.company}</strong><small className="text-slate-500">{row.leadCode || 'Direct Client Master'} · {row.status}</small></span><span className={`rounded-full px-3 py-1 text-xs font-black ${row.analysis.percentage === 100 ? 'bg-emerald-100 text-emerald-800' : 'bg-orange-100 text-orange-800'}`}>{row.analysis.percentage}%</span></button>) : <p className="p-8 text-center text-sm font-bold text-slate-400">No Client Master created in this period.</p>}</div></article> }
function LeadList({ leads }) { return <section className="mt-4 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h3 className="flex items-center gap-2 font-black"><FileText className="h-5 w-5 text-sky-600"/>Lead List</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase text-slate-500"><tr><th className="p-3">Lead ID</th><th>Company</th><th>Status</th><th>Services</th><th>Client Master</th><th>Created</th></tr></thead><tbody>{leads.map((lead)=><tr key={lead.id} className="border-t"><td className="p-3 font-black text-emerald-700">{lead.leadCode || '-'}</td><td className="font-bold">{lead.company}</td><td>{lead.status || '-'}</td><td className="max-w-xs text-xs">{lead.services.join(', ') || '-'}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${lead.hasClientMaster ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{lead.hasClientMaster ? 'Created' : 'Not created'}</span></td><td className="text-xs">{formatDateTime(lead.createdAt)}</td></tr>)}</tbody></table></div></section> }
