const express = require('express');
const router = express.Router();
const clientCtrl = require('../controllers/clientController');
const reviewCtrl = require('../controllers/clientComplianceReviewController');
const purchaseCtrl = require('../controllers/purchaseDataController');
const { requireAuth, requireRoles } = require('../middleware/auth');
const { ADMIN_ROLES, CLIENT_APPROVAL_ROLES } = require('../constants/roles');

router.get('/', requireAuth, clientCtrl.listClients);
router.get('/discovery/search', requireAuth, clientCtrl.searchClientMasterCompanies);
router.get('/discovery/services', requireAuth, clientCtrl.listClientMasterServices);
router.get('/discovery/catalog', requireAuth, clientCtrl.listClientMasterCatalog);
router.get('/pending-approvals', requireAuth, clientCtrl.listPendingApprovals);
router.patch('/pending-approvals/clients/approve-all', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), clientCtrl.approveAllPendingClients);
router.post('/bulk', requireAuth, requireRoles(ADMIN_ROLES), clientCtrl.bulkCreateClients);
router.post('/years/bulk', requireAuth, requireRoles(ADMIN_ROLES), clientCtrl.bulkUpdateClientYears);
router.post('/', requireAuth, clientCtrl.createClient);
router.get('/:id', requireAuth, clientCtrl.getClient);
router.get('/:id/annual-return/po-status', requireAuth, clientCtrl.getAnnualReturnPoStatus);
router.get('/:id/purchase-data', requireAuth, purchaseCtrl.getPurchaseData);
router.put('/:id/purchase-data/checklist', requireAuth, purchaseCtrl.updateChecklist);
router.put('/:id/purchase-data/screenshots', requireAuth, purchaseCtrl.updateScreenshots);
router.post('/:id/purchase-imports/:source', requireAuth, purchaseCtrl.importPurchaseRows);
router.delete('/:id/purchase-imports/:source', requireAuth, purchaseCtrl.removePurchaseImport);
router.get('/:id/purchase-data/rows', requireAuth, purchaseCtrl.listPurchaseRows);
router.get('/:id/purchase-reconciliation', requireAuth, purchaseCtrl.getReconciliation);
router.get('/:id/purchase-imports/:source/errors', requireAuth, purchaseCtrl.getPurchaseErrors);
router.post('/:id/purchase-data/submit', requireAuth, purchaseCtrl.submitPurchaseData);
router.post('/:id/purchase-data/manager-review', requireAuth, purchaseCtrl.managerReview);
router.post('/:id/purchase-data/compliance-review', requireAuth, purchaseCtrl.complianceReview);
router.get('/:id/compliance-review', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), reviewCtrl.getReview);
router.put('/:id/compliance-review/sections/:sectionKey', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), reviewCtrl.updateSection);
router.post('/:id/compliance-review/decision', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), reviewCtrl.completeReview);
router.patch('/:id/approval', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), clientCtrl.updateClientApproval);
router.put('/:id/annual-return', requireAuth, clientCtrl.updateAnnualReturn);
router.put('/:id', requireAuth, clientCtrl.updateClient);

module.exports = router;
