import React, { useEffect, useMemo, useState } from 'react';
import { Eye, RefreshCw, X } from 'lucide-react';
import DashboardShell from '../components/dashboard/DashboardShell';
import api from '../services/api';
import { API_ENDPOINTS } from '../services/apiEndpoints';
import { fetchCcpLeads, fetchCcpLeadHistory } from '../services/ccpApi';

function idFor(row = {}) { return row._id || row.id || row.sourceLeadId || row.leadCode || ''; }
function dateFor(row = {}) { return row.leadDate || row.createdAt || row.importedCreatedAt || ''; }
function oldDraft(row) {
  const date = new Date(dateFor(row) || 0);
  return date.getTime() && Date.now() - date.getTime() >= 30 * 86400000 && String(row.workflowStatus || '').toLowerCase() === 'draft' && !row.closedBy && !row.closedByText;
}
function value(input) { return input === null || input === undefined || input === '' ? '-' : typeof input === 'object' ? (input.name || input.email || JSON.stringify(input)) : String(input); }

export default function PendingLeads() {
  const [currentUser, setCurrentUser] = useState(() => { try { return JSON.parse(localStorage.getItem('user') || 'null'); } catch { return null; } });
  const [leads, setLeads] = useState([]);
  const [selected, setSelected] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const rows = useMemo(() => leads.filter(oldDraft), [leads]);
  async function load() {
    setLoading(true);
    const [me, result] = await Promise.allSettled([api.get(API_ENDPOINTS.auth.me), fetchCcpLeads()]);
    if (me.status === 'fulfilled') setCurrentUser(me.value.data?.user);
    setLeads(result.status === 'fulfilled' ? (result.value.data?.leads || []) : []);
    setLoading(false);
  }
  useEffect(() => { load(); }, []);
  async function view(row) {
    setSelected(row); setHistory([]);
    const result = await Promise.allSettled([api.get(API_ENDPOINTS.leads.history(idFor(row))), fetchCcpLeadHistory(idFor(row), { leadCode: row.leadCode, company: row.company })]);
    setHistory(result.flatMap((item) => item.status === 'fulfilled' ? (item.value.data?.events || []) : []).sort((a, b) => new Date(b.at || 0) - new Date(a.at || 0)));
  }
  return <DashboardShell currentUser={currentUser}>
    <div className="p-6">
      <div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Super Admin Review</p><h1 className="text-3xl font-black">Pending Leads</h1><p className="mt-1 font-bold text-slate-500">Draft leads unclosed for 30 days or more.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-black text-white"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>
      <div className="overflow-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Sr. No.', 'Lead Date', 'Lead Generated By', 'Company', 'Services', 'FY Years', 'Action'].map((item) => <th className="px-4 py-4" key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t" key={idFor(row)}><td className="px-4 py-4 font-black">{index + 1}</td><td className="px-4 py-4">{value(dateFor(row)).slice(0, 10)}</td><td className="px-4 py-4">{value(row.importedCreatedBy)}</td><td className="px-4 py-4 font-black">{value(row.company)}</td><td className="px-4 py-4">{value(row.servicesOffered)}</td><td className="px-4 py-4">{value(row.firstAnnualReturnYearApplicable || row.serviceSelections?.map((item) => item.firstAnnualReturnYearApplicable).filter(Boolean).join(', '))}</td><td className="px-4 py-4"><button onClick={() => view(row)} className="grid h-10 w-10 place-items-center rounded-xl border border-emerald-200 text-emerald-700"><Eye className="h-4 w-4" /></button></td></tr>)}{!rows.length && <tr><td colSpan={7} className="p-12 text-center font-black text-slate-400">{loading ? 'Loading pending leads...' : 'No 30-day pending leads.'}</td></tr>}</tbody></table></div>
    </div>
    {selected && <div className="fixed inset-0 z-[100] overflow-auto bg-slate-950/45 p-5 backdrop-blur-sm"><section className="mx-auto max-w-6xl rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-6"><div><p className="text-xs font-black uppercase text-emerald-700">Complete Lead Data</p><h2 className="text-2xl font-black">{selected.company}</h2></div><button onClick={() => setSelected(null)} className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><X /></button></header><div className="grid gap-6 p-6 lg:grid-cols-2"><DetailTable title="Lead Information" data={selected} /><div><h3 className="mb-3 text-lg font-black">Full Follow-up History</h3><div className="space-y-3">{history.map((item, index) => <div key={item.id || index} className="rounded-xl border p-4"><strong>{item.title || item.type}</strong><p className="mt-1 text-sm text-slate-600">{item.description || '-'}</p><small>{value(item.actor)} · {value(item.at)}</small></div>)}{!history.length && <p className="rounded-xl bg-slate-50 p-6 text-center font-bold text-slate-400">No history available.</p>}</div></div></div></section></div>}
  </DashboardShell>;
}

function DetailTable({ title, data }) {
  const ignored = new Set(['serviceSelections', 'addresses', 'contacts', 'assignments', 'followUpHistory']);
  return <div><h3 className="mb-3 text-lg font-black">{title}</h3><div className="overflow-hidden rounded-xl border"><table className="w-full text-sm"><tbody>{Object.entries(data || {}).filter(([key]) => !ignored.has(key)).map(([key, item]) => <tr className="border-t first:border-0" key={key}><th className="w-2/5 bg-slate-50 px-4 py-3 text-left">{key.replace(/([A-Z])/g, ' $1')}</th><td className="break-all px-4 py-3">{value(item)}</td></tr>)}</tbody></table></div></div>;
}
