import React, { useEffect, useMemo, useState } from 'react'
import { ArrowDownToLine, ArrowUpFromLine, CheckCircle2, DatabaseZap, RefreshCw, Search, UsersRound } from 'lucide-react'
import DashboardShell from '../components/dashboard/DashboardShell'
import api, { API_ENDPOINTS, readApiError, storeSessionUser } from '../services/api'

const cachedUser = () => { try { return JSON.parse(localStorage.getItem('user') || '{}') } catch { return {} } }
const badge = (count, activeClass) => count ? <span className={`inline-flex min-w-16 items-center justify-center rounded-full px-3 py-1 text-xs font-black ${activeClass}`}>{count}</span> : <span className="inline-flex min-w-16 items-center justify-center rounded-full bg-rose-50 px-3 py-1 text-xs font-black text-rose-500">Not added</span>

function Stat({ icon: Icon, label, value, detail, color }) {
  return <div className="relative overflow-hidden rounded-3xl border border-white bg-white p-5 shadow-[0_18px_55px_-34px_rgba(15,23,42,.5)] transition duration-300 hover:-translate-y-1"><div className={`absolute -right-6 -top-8 h-24 w-24 rounded-full opacity-20 blur-xl ${color}`}/><div className="relative flex items-start justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p><p className="mt-2 text-xs font-semibold text-slate-500">{detail}</p></div><span className={`grid h-12 w-12 place-items-center rounded-2xl text-white ${color}`}><Icon size={22}/></span></div></div>
}

export default function PurchaseSalesDashboard() {
  const [currentUser, setCurrentUser] = useState(cachedUser)
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  async function load() {
    setLoading(true); setError('')
    try {
      const [insights, me] = await Promise.all([api.get(API_ENDPOINTS.dashboardInsights.purchaseSales), api.get(API_ENDPOINTS.auth.me).catch(() => null)])
      setData(insights.data)
      if (me?.data?.user) setCurrentUser(storeSessionUser(me.data.user))
    } catch (err) { setError(readApiError(err, 'Purchase & Sales dashboard could not be loaded.')) }
    finally { setLoading(false) }
  }
  useEffect(() => { load() }, [])
  const clients = useMemo(() => (data?.clients || []).filter((row) => `${row.clientName} ${row.financialYears?.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [data, query])
  const summary = data?.summary || {}
  const coverage = summary.clients ? Math.round((summary.complete || 0) / summary.clients * 100) : 0

  return <DashboardShell currentUser={currentUser}><div className="min-h-full bg-[radial-gradient(circle_at_10%_0%,_#ffedd5_0,_transparent_28%),linear-gradient(135deg,#fff7ed,#f8fafc_48%,#ecfdf5)] p-4 sm:p-6 lg:p-8">
    <header className="relative overflow-hidden rounded-[2rem] border border-orange-200 bg-gradient-to-r from-orange-500 via-amber-500 to-emerald-600 p-7 text-white shadow-2xl shadow-orange-900/15"><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full border-[38px] border-white/10"/><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.3em] text-orange-100">Data availability & completion</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Purchase & Sales Dashboard</h1><p className="mt-2 max-w-2xl text-sm text-white/80">Users see their own client portfolio, managers see their reporting team, and administrators see the complete organisation.</p></div><button onClick={load} disabled={loading} className="flex items-center gap-2 rounded-2xl bg-white/15 px-4 py-3 text-sm font-black backdrop-blur transition hover:bg-white/25"><RefreshCw size={17} className={loading ? 'animate-spin' : ''}/>Refresh</button></div></header>
    {error && <div className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={UsersRound} label="Client count" value={summary.clients || 0} detail="Total visible clients" color="bg-gradient-to-br from-sky-400 to-blue-600"/><Stat icon={ArrowDownToLine} label="Purchased data" value={summary.purchased || 0} detail="Available yearly records" color="bg-gradient-to-br from-orange-400 to-rose-500"/><Stat icon={ArrowUpFromLine} label="Sales data" value={summary.sales || 0} detail="Available yearly records" color="bg-gradient-to-br from-violet-500 to-purple-600"/><Stat icon={CheckCircle2} label="Both available" value={summary.complete || 0} detail={`${coverage}% client coverage`} color="bg-gradient-to-br from-emerald-400 to-teal-600"/></div>
    {loading && !data ? <div className="mt-6 h-72 animate-pulse rounded-3xl bg-white/70"/> : <>
      <section className="mt-6 overflow-hidden rounded-3xl border border-orange-100 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5"><div><h2 className="font-black text-slate-900">User-wise data coverage</h2><p className="text-xs text-slate-500">Correct numeric client counts and purchase/sales record totals; no edit actions.</p></div><span className="rounded-full bg-orange-50 px-4 py-2 text-xs font-black text-orange-600">Role-scoped live data</span></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gradient-to-r from-orange-50 to-amber-50 text-[11px] uppercase tracking-wider text-slate-600"><tr><th className="px-5 py-3">User name</th><th className="px-5 py-3">Clients</th><th className="px-5 py-3">Purchased records</th><th className="px-5 py-3">Sales records</th><th className="px-5 py-3">Both available</th></tr></thead><tbody className="divide-y divide-slate-100">{(data?.users || []).map((row) => <tr key={row.userId || row.userName} className="transition hover:bg-orange-50/40"><td className="px-5 py-4"><p className="font-black text-slate-900">{row.userName}</p><p className="text-xs capitalize text-slate-400">{row.role || 'Team member'}</p></td><td className="px-5 py-4 text-lg font-black text-slate-800">{row.clients}</td><td className="px-5 py-4">{badge(row.purchased, 'bg-orange-100 text-orange-700')}</td><td className="px-5 py-4">{badge(row.sales, 'bg-violet-100 text-violet-700')}</td><td className="px-5 py-4">{badge(row.complete, 'bg-emerald-100 text-emerald-700')}</td></tr>)}</tbody></table></div></section>
      <section className="mt-6 overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5"><div><h2 className="font-black text-slate-900">Client data matrix</h2><p className="text-xs text-slate-500">Availability by client and financial year</p></div><label className="flex min-w-64 items-center gap-2 rounded-xl border border-slate-200 px-3 py-2"><Search size={16} className="text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search client or year" className="w-full bg-transparent text-sm outline-none"/></label></div><div className="max-h-[560px] overflow-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Client</th><th className="px-5 py-3">Financial year</th><th className="px-5 py-3">Purchase</th><th className="px-5 py-3">Sales</th><th className="px-5 py-3">Coverage</th></tr></thead><tbody className="divide-y divide-slate-100">{clients.map((row) => { const complete = row.purchaseCount > 0 && row.salesCount > 0; return <tr key={row.clientId} className="hover:bg-slate-50"><td className="px-5 py-4 font-black text-slate-800">{row.clientName}</td><td className="px-5 py-4">{row.financialYears?.join(', ') || 'Not started'}</td><td className="px-5 py-4">{badge(row.purchaseCount, 'bg-orange-100 text-orange-700')}</td><td className="px-5 py-4">{badge(row.salesCount, 'bg-violet-100 text-violet-700')}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-black ${complete ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}><DatabaseZap size={14}/>{complete ? 'Complete' : 'In progress'}</span></td></tr>})}</tbody></table>{!clients.length && <p className="py-12 text-center text-sm text-slate-400">No client data matches this search.</p>}</div></section>
    </>}
  </div></DashboardShell>
}
