import React, { useEffect, useState } from 'react';
import { Download, RefreshCw, Users, FolderOpen, CheckCircle2, Clock3 } from 'lucide-react';
import DashboardShell from '../components/dashboard/DashboardShell';
import api from '../services/api';
import { API_ENDPOINTS } from '../services/apiEndpoints';

export default function SuperAdminDashboard() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('user') || 'null'));
  const [data, setData] = useState({ summary: {}, users: [] });
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const res = await api.get(API_ENDPOINTS.auth.superAdminOverview); setData(res.data || res); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const downloadPdf = async () => { const { jsPDF } = await import('jspdf'); const pdf = new jsPDF(); pdf.setFontSize(18); pdf.text('Ananttattva Super Admin Report', 14, 18); pdf.setFontSize(10); pdf.text(`Generated: ${new Date().toLocaleString('en-IN')}`, 14, 26); let y = 38; [['Total users', data.summary.users], ['Active users', data.summary.activeUsers], ['Total leads', data.summary.leads], ['Open leads', data.summary.openLeads], ['Closed leads', data.summary.closedLeads]].forEach(([k, v]) => { pdf.text(`${k}: ${v || 0}`, 14, y); y += 8; }); y += 5; pdf.text('User-wise lead report', 14, y); y += 8; data.users.forEach((row) => { if (y > 275) { pdf.addPage(); y = 18; } pdf.text(`${row.name} | Total: ${row.totalLeads} | Open: ${row.openLeads} | Closed: ${row.closedLeads}`, 14, y); y += 7; }); pdf.save('ananttattva-superadmin-report.pdf'); };
  const cards = [['Users', data.summary.users, Users, 'bg-indigo-50 text-indigo-700'], ['Active users', data.summary.activeUsers, CheckCircle2, 'bg-emerald-50 text-emerald-700'], ['Open leads', data.summary.openLeads, Clock3, 'bg-amber-50 text-amber-700'], ['Closed leads', data.summary.closedLeads, FolderOpen, 'bg-teal-50 text-teal-700']];
  return <DashboardShell currentUser={user} onOpenProfile={() => {}}><div className="p-5 lg:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.25em] text-orange-500">Executive control center</p><h1 className="mt-1 text-3xl font-black text-slate-950">Super Admin Dashboard</h1><p className="mt-2 text-sm font-semibold text-slate-500">Complete user, lead open/close and performance analysis.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border bg-white px-4 py-3 font-black text-teal-700"><RefreshCw className="mr-2 inline h-4 w-4"/>Refresh</button><button onClick={downloadPdf} className="rounded-xl bg-orange-500 px-4 py-3 font-black text-white"><Download className="mr-2 inline h-4 w-4"/>Download PDF</button></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mb-5 grid h-11 w-11 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5"/></div><p className="text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-4xl font-black text-slate-950">{value || 0}</p></article>)}</div><section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black">User-wise Lead Analysis</h2><p className="text-sm text-slate-500">Every user’s total, open and closed leads.</p></div><div className="overflow-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['User','Role / Team','Status','Total leads','Open leads','Closed leads','Last login'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{data.users.map(row=><tr key={row.id} className="border-t"><td className="p-4"><b>{row.name}</b><small className="block text-slate-500">{row.email}</small></td><td className="p-4">{row.role}<small className="block text-slate-500">{row.team}</small></td><td className="p-4"><span className={row.active ? 'rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700' : 'rounded-full bg-slate-200 px-3 py-1 text-xs font-black text-slate-600'}>{row.active ? 'Active' : 'Inactive'}</span></td><td className="p-4 font-black">{row.totalLeads}</td><td className="p-4 font-black text-amber-600">{row.openLeads}</td><td className="p-4 font-black text-emerald-700">{row.closedLeads}</td><td className="p-4 text-sm">{row.lastLogin ? new Date(row.lastLogin).toLocaleString('en-IN') : 'No login yet'}</td></tr>)}{!loading && !data.users.length && <tr><td colSpan="7" className="p-10 text-center">No records found.</td></tr>}</tbody></table></div></section></div></DashboardShell>;
}
