import React, { useCallback, useEffect, useState } from 'react'
import api from '../../services/api'

function ReasonDialog({ title, onClose, onSubmit }) {
  const [reason, setReason] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  async function submit(event) { event.preventDefault(); setSaving(true); try { await onSubmit(reason.trim()); onClose() } catch (err) { setError(err.response?.data?.error || 'Unable to save. Please retry.') } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><form role="dialog" aria-modal="true" aria-label={title} onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-black text-slate-900">{title}</h2><p className="mt-2 text-sm text-slate-500">Your reason is recorded in the approval history. Editing stays locked during approval and after final deactivation.</p><label className="mt-5 block text-sm font-bold">Reason / Notes<textarea autoFocus required maxLength={4000} value={reason} onChange={(event) => setReason(event.target.value)} rows={5} className="mt-2 w-full rounded-xl border p-3" /></label>{error && <p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" disabled={saving} onClick={onClose} className="rounded-lg border px-4 py-2">Cancel</button><button type="submit" disabled={saving || !reason.trim()} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Submit'}</button></div></form></div>
}
export function DeactivationButton({ clientId, onChanged }) {
  const [open, setOpen] = useState(false)
  return <><button type="button" disabled={!clientId} onClick={() => setOpen(true)} className="rounded-lg border border-rose-200 px-2 py-2 text-xs font-bold text-rose-700" title="Request client deactivation">Deactivate</button>{open && <ReasonDialog title="Request client deactivation" onClose={() => setOpen(false)} onSubmit={async (reason) => { await api.post(`/clients/${clientId}/deactivation`, { reason }); onChanged?.() }} />}</>
}
export function DeactivationApprovals({ onCountChange }) {
  const [rows, setRows] = useState([])
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  const [decision, setDecision] = useState(null)
  const load = useCallback(async () => { setLoading(true); try { const response = await api.get('/clients/deactivation-requests'); setRows(response.data.requests || []); onCountChange?.((response.data.requests || []).filter((row) => row.canDecide).length); setError('') } catch (err) { setError(err.response?.data?.error || 'Unable to load requests.') } finally { setLoading(false) } }, [onCountChange])
  useEffect(() => { load() }, [load])
  return <section className="p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-black">Client Deactivation Approvals</h2><p className="mt-1 text-sm text-slate-500">User request → Reporting manager → Admin / Super Admin. Rejection restores active access.</p></div><button type="button" onClick={load} disabled={loading} className="rounded-lg border px-3 py-2">Refresh</button></div>{error && <p role="alert" className="mb-4 text-rose-600">{error}</p>}<div className="overflow-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Client', 'Requested by', 'Status', 'Reason & approval history', 'Actions'].map((name) => <th key={name} className="p-3">{name}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row._id} className="border-t"><td className="p-3 font-bold">{row.clientName}</td><td className="p-3">{row.requestedBy?.name || row.requestedBy?.email}</td><td className="p-3"><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold">{row.status.replaceAll('_', ' ')}</span></td><td className="max-w-lg p-3">{row.history.map((event, index) => <div key={index} className="mb-3"><p className="text-xs font-bold text-slate-500">{event.action.replaceAll('_', ' ')} · {event.by?.name || event.by?.email || 'User'} · {new Date(event.at).toLocaleString()}</p><p className="mt-1 whitespace-pre-wrap break-words">{event.reason}</p></div>)}</td><td className="p-3">{row.canDecide ? <div className="flex gap-2">{['APPROVE', 'REJECT'].map((action) => <button key={action} type="button" onClick={() => setDecision({ row, action })} className={`rounded-lg px-3 py-2 font-bold ${action === 'APPROVE' ? 'bg-emerald-700 text-white' : 'bg-rose-50 text-rose-700'}`}>{action === 'APPROVE' ? 'Approve' : 'Reject'}</button>)}</div> : '—'}</td></tr>)}{!rows.length && <tr><td colSpan={5} className="p-10 text-center text-slate-500">{loading ? 'Loading requests…' : 'No client deactivation requests.'}</td></tr>}</tbody></table></div>{decision && <ReasonDialog title={`${decision.action === 'APPROVE' ? 'Approve' : 'Reject'} · ${decision.row.clientName}`} onClose={() => setDecision(null)} onSubmit={async (reason) => { await api.post(`/clients/deactivation-requests/${decision.row._id}/decision`, { reason, decision: decision.action }); await load() }} />}</section>
}
